# Librería `Numpy`

La **visualización gráfica** se basa en la idea de manipular información almacenada en unas estructuras conocidas como *vectores* y *matrices*. En Python la única forma de simular estas estructuras es usando listas, pero resulta que  son estas son muy limitadas respecto a las funciones matemáticas que permiten. `Numpy` viene a solucionar esa carencia Proporciona un poderoso objeto de matriz multidimensional llamado `ndarray`, junto con funciones para operar en estas matrices.

**NumPy** es una de las bibliotecas fundamentales en Python para **computación científica** y **análisis numérico**. 

Enseguida se enlistan algunas  características importantes de `NumPy`:

* **Arrays multidimensionales:** El objeto `ndarray` permite almacenar y manipular datos de manera eficiente. Estas arreglos pueden tener cualquier número de dimensiones y contener elementos del mismo tipo. Los `arrays` en `NumPy` son más eficientes en términos de memoria y tiempo de ejecución en comparación con las listas de Python.

* **Rápida ejecución de operaciones matemáticas:**  `NumPy` permite realizar operaciones matemáticas con matrices de manera eficiente. Esto es especialmente beneficioso cuando se trabaja con conjuntos de datos grandes o algoritmos numéricamente intensivos.

* **Funciones de álgebra lineal:**  `NumPy` proporciona una amplia gama de funciones para realizar operaciones de ***Álgebra lineal***, como *multiplicación de matrices*, *descomposición de valores singulares*, *descomposición LU*, *inversión de matrices* y mucho más.

* **Generación de números aleatorios:** `NumPy` incluye un módulo llamado `random` que permite generar números aleatorios de diversas **distribuciones estadísticas**. Esto es útil para simular datos o realizar experimentos numéricos.

* **Integración con otras bibliotecas:** `NumPy` se utiliza ampliamente como base para otras bibliotecas científicas en Python, como `SciPy` (biblioteca de cálculo científico), `pandas` (biblioteca de manipulación de datos) y `scikit-learn` (biblioteca de aprendizaje automático).

## Importando `Numpy`

In [ ]:
import numpy as np

## Crear un arreglo a partir  de una lista 

In [ ]:
arreglo = np.array([1, 2, 3, 4, 5])
print(arreglo)

**Observación:** Al imprimir un array a diferencia de las listas sus elementos no están separados por comas.

In [ ]:
print(type(arreglo))

## Creando un array

In [ ]:
import numpy as np

arreglo = np.array([1, 2, 3, 4, 5]) 
print(arreglo)


In [ ]:

arreglo2d = np.array([list(range(1,4)), list(range(4,7)), list(range(7,10))])
print(arreglo2d)

## Atributos de un ndarray

Existen varios atributos y funciones que describen las características de un array.

* `a.ndim`: Devuelve el número de dimensiones del array a.

* `a.shape`: Devuelve una tupla con las dimensiones del array a.

* `a.size`: Devuelve el número de elementos del array a.

* `a.dtype`: Devuelve el tipo de datos de los elementos del array a.

Podemos consultar la **dimensión** y **forma** de un array con sus propiedades `ndim` y `shape`

In [ ]:
print(arreglo.shape)   # Muestra las dimensiones del ndarray
print(arreglo.ndim)    # Muestra el número de dimensiones del ndarray
print(arreglo.size)    # Muestra el número total de elementos en el ndarray

Ahora bien, **podemos definir un array a partir de una lista anidada formada por dos sublistas**:

In [ ]:
array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(array)
print(array.ndim)
print(array.shape)
print(array.size)

El array se muestra como una tabla de 2 filas con 5 columnas, números que precisamente concuerdan con la forma (2, 5).

Estas estructuras formadas por filas y columnas parecidas a una tabla tienen dos dimensiones, anchura y altura (por eso nos dice que tiene 2 dimensiones). También se conocen como **vectores multidimensionales** o **matrices**.

## Tipos de array

También podemos consultar el tipo de los arrays.

In [ ]:
array = np.array([1, 2, 3, 4, 5])
print(array.dtype)

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6.1234])
print(array.dtype)

In [ ]:
array = np.array(["Hola_5", "que", "tal"])
print(array.dtype)

In [ ]:
array = np.array(["Hola", 1234, 3.1415])
print(array.dtype)
#print(array)

## Acceso a los elementos de un array

Para acceder a los elementos contenidos en un array se usan índices al igual que para acceder a los elementos de una lista, pero indicando los índices de cada dimensión separados por comas.

Al igual que para listas, los índices de cada dimensión comienzan en 0.

In [ ]:
arreglo = np.array([1, 2, 3, 4, 5])
print(arreglo[0]) 

In [ ]:
arreglo2d = np.array([list(range(1,4)), list(range(4,7)), list(range(7,10))])
print(arreglo2d)

print(arreglo2d[0])
print(arreglo2d[-1,-1])

In [ ]:
print(arreglo2d[0][2])

In [ ]:
arreglo2d[0] = 11
print(arreglo2d)

### Slicing. 



También es posible obtener subarrays con el operador dos puntos `:` Se basa en dos índices, uno de inicio y otro de fin separados por dos puntos para cada dimensión. Si dejamos los índices vacíos se toman por defecto el principio y el final.

In [ ]:
arreglo = np.array([1, 2, 3, 4, 5]) 
print(arreglo[1:4])   
print(arreglo[:])
print(arreglo[0:-1])

In [ ]:
arreglo[1:-1]=0
print(arreglo[:])

In [ ]:
arreglo2d = np.array([list(range(1,4)), list(range(4,7)), list(range(7,10))])
print(arreglo2d)


In [ ]:
print(arreglo2d[:][:])
print(arreglo2d[:2][:])
print(arreglo2d[:][:1])

In [ ]:
arreglo2d[:2][:2] = 0
print(arreglo2d[:][:])

## Copia de un arreglo

En Python, cuando copias una estructura como una lista o un array, debes distinguir entre:

* `Copia por referencia`: Ambas variables apuntan al mismo objeto.

* `Copia  superficial`: Se copia el contenedor, pero los elementos siguen compartidos (relevante con estructuras anidadas). Es decir, por ejemplo si se copia superficielmente un  arrays de dos dimensiones, todos los cambios realizados en un subarray se verán reflejados en el original.

### Copia por referencia

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])


arr2 = arr1
arr2[0] = 100

print(arr1)  


[100   2   3]


### Copia con `np.copy()`

In [ ]:

arr1 = np.array([1, 2, 3])
arr2 = np.copy(arr1)

arr2[0] = 100
print(arr1) 
print(arr2) 

## Filtrado de elementos de un array

Una característica muy útil de los arrays es que es muy fácil obtener otro array con los elementos que cumplen una condición

`a[condicion]`: Devuelve una lista con los elementos del array `a` que cumplen la condición `condicion`.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

[2 4 6]
[4 6]


In [ ]:
print(a[a % 2 == 0])


In [ ]:
print(a[(a % 2 == 0) &  (a > 2)])

In [4]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [6]:
resultado = b[b > 4]
print(resultado)

[5 6 7 8 9]


## Operaciones matemáticas entre arreglos

Existen dos formas de realizar operaciones matemáticas con arrays: a nivel de elemento y a nivel de array.

Las operaciones a nivel de elemento operan los elementos que ocupan la misma posición en dos arrays. Se necesitan, por tanto, dos arrays con las mismas dimensiones y el resultado es una array de la misma dimensión.

Los operadores matemáticos `+, -, *, /, %, **` se utilizan para la realizar suma, resta, producto, cociente, resto y potencia a nivel de elemento respectivamente.

### Suma

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#print(np.add(a, b))        
print(a+b)


In [ ]:
arr_5 = np.array([[1,2],[3,4]])
arr_6 = np.array([[5,6],[7,8]])

suma = arr_5 + arr_6
print(suma)

### Resta

In [7]:
print(np.subtract(a, b))   
resta = a-b
print(resta)




ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

### Multiplicación

In [ ]:
print(np.multiply(a, b))   
print(a*b)

# Multiplicación por escalar
print(5*a)


### División

In [ ]:
#print(np.divide(a, b))     
print(a/b)

#Divisiones interesantes
print(1/a)


### Potencia

In [ ]:
print(a**2)

In [8]:
#Potencias interesantes

print(a**-1.)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


## Álgebra Matricial (submódulo `linalg`)

`Numpy` incorpora funciones para realizar las principales operaciones algebraicas con vectores y matrices. La mayoría de los métodos algebráicos se agrupan en el submódulo `linalg`.

### Producto escalar de dos vectores

Para realizar el producto escalar de dos vectores se utiliza el operador `@` o el siguiente método: `u.dot(v)`: Devuelve el producto escalar de los vectores u y v.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])
print(a @ b)

### Módulo de un vector

Para calcular el módulo de un vector se utiliza el siguiente método:

`norm(v)`: Devuelve el módulo del vector `v`.

In [ ]:
import numpy as np
a = np.array([3, 4])
print(np.linalg.norm(a))

### Producto de dos matrices

Para realizar el producto matricial se utiliza el mismo operador `@` y método que para el producto escalar de vectores:

`a.dot(b)`: Devuelve el producto matricial de las matrices `a` y `b` siempre y cuando sus dimensiones sean compatibles.

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)
print(a.dot(b))

### Matriz Transpuesta

Para trasponer una matriz se utiliza el método

`a.T` : Devuelve la matriz traspuesta de la matriz `a`.

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)

### Traza de una matriz

La traza de una matriz cuadrada se calcula con el siguiente método:

`a.trace()`: Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada `a`.

In [9]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())

15


### Determinante de una matriz

El determinante de una matriz cuadrada se calcula con la siguiente función:

`det(a)`: Devuelve el determinante de la matriz cuadrada `a`.

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

### La inversa de una matriz 

La inversa de una matriz se calcula con la siguiente función:

`inv(a)`: Devuelve la matriz inversa de la matriz cuadrada `a`.

### Matriz inversa

La inversa de una matriz se calcula con la siguiente función:

`inv(a)` : Devuelve la matriz inversa de la matriz cuadrada `a`.

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

### Autovalores de una matriz

Los autovalores de una matriz cuadrada se calculan con la siguiente función:

`eigvals(a)`: Devuelve los autovalores de la matriz cuadrada `a`.

In [ ]:
import numpy as np
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))

### Autovectores de una matriz

Los autovectores de una matriz cuadrada se calculan con la siguiente función:

`eig(a)`: Devuelve los autovalores y los autovectores asociados de la matriz cuadrada `a`.

## Funciones estadísticas

In [ ]:
arreglo = np.array([1, 2, 3, 4, 5])

print(np.mean(arreglo))       # Calcula la media del ndarray
print(np.median(arreglo))     # Calcula la mediana del ndarray
print(np.std(arreglo))        # Calcula la desviación estándar del ndarray
print(np.min(arreglo))        # Encuentra el valor mínimo del ndarray
print(np.max(arreglo))        # Encuentra el valor máximo del ndarray

### Solución de un sistema de ecuaciones

Para resolver un sistema de ecuaciones lineales se utiliza la función siguiente:

`solve(A, B)`: Devuelve la solución del sistema de ecuaciones lineales con los coeficientes de la matriz `A` y los términos independientes de la matriz `B`.

## Arrays pregenerados

rear arrays a partir de listas puede ser muy tedioso, por eso numpy integra varias funciones muy útiles para generar arrays de uso común en el álgebra de matrices

In [10]:
import numpy as np
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2 
A = np.array([[1, 2], [3, 5]])
B = np.array([1, 2])
print(np.linalg.solve(A, B))

[-1.  1.]


### Array de ceros

Un array de ceros es cuando todos sus elementos son ceros. Podemos generarlos con el método zeros de Numpy:

In [ ]:
import numpy as np
print(np.zeros(3))


Evidentemente podemos generar arrays multidimensionales, pero para ello tenemos que pasarle al método una lista o tupla con la longitud de sus dimensiones:

In [ ]:
np.zeros([3,3])

In [ ]:
m = np.zeros([2,2])
m[0][0] = np.zeros(2)

### Array de unos

Lo mismo podemos hacer pero utilizando el método ones:

In [ ]:
print(np.ones([3,3]))

### Array  identidad

Los arrays de identidad son matrices cuadradas (con el mismo número de filas que de columnas) donde todos los valores son ceros a excepción de la diagonal donde son unos. Podemos generarlos con el método eye:

In [ ]:
np.eye(2)

### Array de rangos

 también es posible generar arrays a partir de un rango de valores. Para hacerlo utilizaríamos el método arange:

In [ ]:
# Rango de 0 a 3
np.arange(4)



In [ ]:
# Rango 0 a 4 decimal
np.arange(4.)


In [ ]:

# Rango de -3 a 4
np.arange(-3, 3)


In [ ]:

# Rango de 0 a 20 cada 5 números
np.arange(0, 20, 5)

## Consideraciones importantes

Los `arrays` tienen una característica muy especial y es que **se encuentran referenciados en la memoria**.
Esto significa que a la hora de trabajar con subarrays todos los cambios que hagamos se verán reflejados en el array original. 

In [15]:
arreglo = np.arange(0, 50, 0.1)

print(arreglo)


sub_arreglo = arreglo[0:4]

print(sub_arreglo)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 

Modifiquemos el subarray:

In [ ]:
sub_arreglo[:] = 0
sub_arreglo
arreglo

Esto ocurre porque numpy hace una gestión óptima de la memoria y no va a malgastarla creando copias por valor. Para **crear una copia** real de un array y no modificar el original, tendremos que utilizar el método `copy`:

In [ ]:
arreglo = np.arange(0, 51, 5)
sub_arreglo = arreglo.copy()
sub_arreglo

In [ ]:
sub_arreglo[:] = 0
sub_arreglo
arreglo

## Fancy index

 Esta propiedad de los arrays nos permite trabajar muy cómodamente con las filas de estos arrays

Vamos a crear una matriz 5x10 llena de ceros:

In [11]:
matrixceros = np.zeros((5,10))


Con `fancy index`, podemos pasarle una lista al array haciendo referencia a las filas donde queremos acceder.

Por ejemplo podemos modificar al vuelo la primera, tercera y última fila:

In [ ]:
matrixceros[[0,2,-1]] = 1
matrixceros

**Observacion:**  La idea es  que realmente las filas simulan sublistas. De hecho podríamos recorrer este 2-array  con un `for` y cada vez que entramos al bucle estamos en una fila:

In [ ]:
for row in matrixceros:
    print(row)

De manera que si quisiéramos darle el mismo valor a cada fila no costaría mucho, sólo deberíamos acceder a través de nuestro índice mágico, que podemos sacarlo por ejemplo con un enumerador:

In [ ]:
for i,row in enumerate(matrixceros):
    matrixceros[i]=11

matrixceros

## Arrays de 3 y más dimensiones

De la misma forma que un array de 2 dimensiones, el truco para crear uno de 3 consiste en anidar listas a 3 niveles de profundidad.

In [ ]:
import numpy as np

# Primer nivel, 2 elementos en ancho
arreglo_1d = np.array(
    [1, 2]
)
arreglo_1d

In [ ]:

# Segundo nivel, 2 elementos en ancho por 2 de alto,
# 4 elementos en total
arreglo_2d = np.array([
    [1, 2],
    [3, 4]
])
arreglo_2d

In [ ]:

# Tercer nivel, 2 elementos en ancho por 2 de alto
# por 2 de profundidad, 8 elementos en total
arreglo_3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
arreglo_3d

In [12]:
import pandas as pd

matriz = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(matriz)
print(df)


   0  1  2
0  1  2  3
1  4  5  6
