# Librería `Numpy`

La **visualización gráfica** se basa en la idea de manipular información almacenada en unas estructuras conocidas como *vectores* y *matrices*. En Python la única forma de simular estas estructuras es usando listas, pero resulta que  son estas son muy limitadas respecto a las funciones matemáticas que permiten. `Numpy` viene a solucionar esa carencia Proporciona un poderoso objeto de matriz multidimensional llamado `ndarray`, junto con funciones para operar en estas matrices.

**NumPy** es una de las bibliotecas fundamentales en Python para **computación científica** y **análisis numérico**.

Enseguida se enlistan algunas  características importantes de `NumPy`:

* **Arrays multidimensionales:** El objeto `ndarray` permite almacenar y manipular datos de manera eficiente. Estas arreglos pueden tener cualquier número de dimensiones y contener elementos del mismo tipo. Los `arrays` en `NumPy` son más eficientes en términos de memoria y tiempo de ejecución en comparación con las listas de Python.

* **Rápida ejecución de operaciones matemáticas:**  `NumPy` permite realizar operaciones matemáticas con matrices de manera eficiente. Esto es especialmente beneficioso cuando se trabaja con conjuntos de datos grandes o algoritmos numéricamente intensivos.

* **Funciones de álgebra lineal:**  `NumPy` proporciona una amplia gama de funciones para realizar operaciones de ***Álgebra lineal***, como *multiplicación de matrices*, *descomposición de valores singulares*, *descomposición LU*, *inversión de matrices* y mucho más.

* **Generación de números aleatorios:** `NumPy` incluye un módulo llamado `random` que permite generar números aleatorios de diversas **distribuciones estadísticas**. Esto es útil para simular datos o realizar experimentos numéricos.

* **Integración con otras bibliotecas:** `NumPy` se utiliza ampliamente como base para otras bibliotecas científicas en Python, como `SciPy` (biblioteca de cálculo científico), `pandas` (biblioteca de manipulación de datos) y `scikit-learn` (biblioteca de aprendizaje automático).

## Importando `Numpy`

In [80]:
import numpy as np

## Crear un arreglo 

### Crear un arreglo a partir  de una lista

In [81]:
import numpy as np
arreglo = np.array([1, 2, 3, 4, 5])
print(arreglo)

[1 2 3 4 5]


**Observación:** Al imprimir un array a diferencia de las listas sus elementos no están separados por comas.

In [82]:
print(type(arreglo))

<class 'numpy.ndarray'>


### Crear un arreglo a partir  de `range`

In [83]:
import numpy as np
arreglo = np.array(range(0,5))
print(arreglo)

[0 1 2 3 4]


### Crear un arreglo a partir  de una tupla

In [84]:
import numpy as np
arreglo = np.array((1,2,4))
print(arreglo)

[1 2 4]


## Atributos de un `ndarray`

Existen varios atributos y funciones que describen las características de un array.

* `array.ndim`: Devuelve el número de dimensiones del array array.

* `array.shape`: Devuelve una tupla con las dimensiones del array array.

* `array.size`: Devuelve el número de elementos del array array.

* `array.dtype`: Devuelve el tipo de datos de los elementos del array array.

### `ndim` y `shape`

Podemos consultar la **dimensión** y **forma** de un array con sus propiedades `ndim` y `shape`

In [85]:
print(arreglo.shape)   # Muestra las dimensiones del ndarray
print(arreglo.ndim)    # Muestra el número de dimensiones del ndarray
print(arreglo.size)    # Muestra el número total de elementos en el ndarray

(3,)
1
3


In [86]:
arreglo2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
print(arreglo2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [87]:
print(arreglo2d.ndim)    # Muestra el número de dimensiones del ndarray
# print(arreglo2d.shape)   # Muestra las dimensiones del ndarray
# print(arreglo2d.size)    # Muestra el número total de elementos en el ndarray

2


In [88]:
arreglo3d = np.array([[[1, 2], [3, 4]],[[1, 2], [3, 4]],[[1, 2], [3, 4]],[[1, 2], [3, 4]],[[1, 2], [3, 4]],[[1, 2], [3, 4]]])
print(arreglo3d)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [89]:
print(arreglo3d.ndim)    # Muestra el número de dimensiones del ndarray
print(arreglo3d.shape)   # Muestra las dimensiones del ndarray
print(arreglo3d.size)    # Muestra el número total de elementos en el ndarray

3
(6, 2, 2)
24


Ahora bien, **podemos definir un array a partir de una lista anidada formada por dos sublistas**:

In [90]:
array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(array)
print(array.ndim)
print(array.shape)
print(array.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
10


In [91]:
arreglo2d = np.array([list(range(1,4)), list(range(4,7)), list(range(7,10))])
print(arreglo2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


El array se muestra como una tabla de 2 filas con 5 columnas, números que precisamente concuerdan con la forma (2, 5).

Estas estructuras formadas por filas y columnas parecidas a una tabla tienen dos dimensiones, anchura y altura (por eso nos dice que tiene 2 dimensiones). También se conocen como **matrices** o **vectores multidimensionales**.

### Tipos de array

También podemos consultar el tipo de los arrays.

In [92]:
array = np.array([1, 2, 3, 4, 5])
print(array.dtype)

int64


In [93]:
array = np.array([1, 2, 3, 4, 5, 6.1234])
print(array.dtype)

float64


In [94]:
array = np.array(["Hola_5", "que", "tal"])
print(array.dtype)

<U6


In [95]:
array = np.array(["Hola", 1234, 3.1415])
print(array.dtype)
#print(array)

<U32


## Acceder a los elementos de un array

Para acceder a los elementos contenidos en un array se usan índices al igual que para acceder a los elementos de una lista, pero indicando los índices de cada dimensión separados por comas.

**Observación:** Al igual que para listas, los índices de cada dimensión comienzan en 0.

In [96]:
arreglo = np.array([1, 2, 3, 4, 5])
print(arreglo[0])

1


In [97]:
arreglo2d = np.array([list(range(1,4)), list(range(4,7)), list(range(7,10))])
print(arreglo2d)

# print(arreglo2d[0])
print(arreglo2d[-1,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [98]:
print(arreglo2d[-1][-1])

9


In [99]:
print(arreglo2d[0][2])

3


In [100]:
arreglo2d[0][0] = 11
print(arreglo2d)

[[11  2  3]
 [ 4  5  6]
 [ 7  8  9]]


### Slicing

Al igual que las listas de Python, las matrices numpy se pueden **cortar**, con lo cual es posible obtener `subarrays` con el operador dos puntos `:`. En este caso este operador, se basa en dos índices, uno de inicio y otro de fin separados por dos puntos para cada dimensión. Si dejamos los índices vacíos se toman por defecto el principio y el final.

In [101]:
arreglo = np.array([1, 2, 3, 4, 5])
print(arreglo[1:4])
# print(arreglo[:])
# print(arreglo[0:-1])

[2 3 4]


In [102]:
arreglo[1:-1] = 0

print(arreglo[:])

[1 0 0 0 5]


Dado que las matrices pueden ser multidimensionales, debe especificar un segmento  (`::`)para cada dimensión de la matriz:

In [103]:
arreglo2d = np.array([list(range(1,4)), list(range(4,7)), list(range(7,10))])
print(arreglo2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [185]:
print(arreglo[:2, 1:3])

[[2 3]
 [5 6]]


In [104]:
# print(arreglo2d[0:2])
# print(arreglo2d[:][:])
print(arreglo2d[:1][:1])

[[1 2 3]]


In [105]:
arreglo2d[:2][:2] = 0
print(arreglo2d[:][:])

[[0 0 0]
 [0 0 0]
 [7 8 9]]


### Enumerate en Arrays

La idea es  que realmente las filas simulan sublistas. De hecho podríamos recorrer este 2-array  con un `for` y cada vez que entramos al bucle estamos en una fila:

In [106]:
import numpy as np
arreglo2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
i=1
for fila in arreglo2d:
    print(f"Fila {i} -> {fila}")
    i +=1

Fila 1 -> [1 2 3 4 5]
Fila 2 -> [ 6  7  8  9 10]


De manera que si quisiéramos darle el mismo valor a cada fila no costaría mucho, sólo deberíamos acceder a través de nuestro *índice mágico*, que podemos sacarlo por ejemplo con `enumerate()`:

In [107]:
print(list(enumerate(arreglo2d)))

[(0, array([1, 2, 3, 4, 5])), (1, array([ 6,  7,  8,  9, 10]))]


In [108]:
for i,fila in enumerate(arreglo2d):
    print(f"Fila {i+1} -> {fila}")
    

Fila 1 -> [1 2 3 4 5]
Fila 2 -> [ 6  7  8  9 10]


In [109]:
for i,row in enumerate(arreglo2d):
    arreglo2d[i]=5

print(arreglo2d)

[[5 5 5 5 5]
 [5 5 5 5 5]]


### Fancy index

 Esta propiedad de los arrays nos permite trabajar muy cómodamente con las filas de estos arrays

In [110]:
matriz = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(matriz)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Con `fancy index`, podemos pasarle una lista al array haciendo referencia a las filas donde queremos acceder.

Por ejemplo podemos modificar la primera, tercera y última fila:

In [111]:
matriz[[0,2,-1]] = 1
print(matriz)

[[ 1  1  1  1  1]
 [ 6  7  8  9 10]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]


## Copia de un arreglo

En Python los arrays de forma similar a las listas también están **se encuentran referenciados en la memoria**., por lo que todos los cambios realizados en un subarray se verán reflejados en el original esto significa que a la hora de trabajar con subarrays todos los cambios que hagamos se verán reflejados en el array original.

In [112]:
arreglo = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(arreglo)

sub_arreglo = arreglo[0:4]

print(sub_arreglo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Modifiquemos subarray `sub_arreglo` e veamos los valores almacenados en `arreglo`

In [113]:
sub_arreglo[:] = 0
sub_arreglo
arreglo

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Esto ocurre porque numpy hace una gestión óptima de la memoria y no va a malgastarla creando copias por valor. Para **crear una copia** real de un array y no modificar el original, tendremos que utilizar el método `array.copy()`:

In [114]:
arreglo = np.arange(0, 51, 5)
sub_arreglo = arreglo.copy()
sub_arreglo

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [115]:
sub_arreglo[:] = 0
sub_arreglo
arreglo

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [116]:
import numpy as np
arreglo = np.array([1, 2, 3, 4, 5])
arreglo2 = arreglo.copy()
arreglo[0]=100
print(arreglo)
print(arreglo2)

[100   2   3   4   5]
[1 2 3 4 5]


## Filtrar de elementos de un array

Una característica muy útil de los arrays es que es muy fácil obtener otro array con los elementos que cumplen una condición

`a[condicion]`: Devuelve una lista con los elementos del array `a` que cumplen la condición `condicion`.

In [117]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [118]:
print(a[(a % 2 == 0)])

[2 4 6]


In [119]:
print(a[(a % 2 == 0) &  (a > 2)])

[4 6]


## Operaciones matemáticas con arreglos

Existen dos formas de realizar operaciones matemáticas con arrays: a nivel de elemento y a nivel de array.

Las operaciones a nivel de elemento operan los elementos que ocupan la misma posición en dos arrays. Se necesitan, por tanto, dos arrays con las mismas dimensiones y el resultado es una array de la misma dimensión.

Los operadores mamemáticos `+, -, *, /, %, **` se utilizan para la realizar suma, resta, producto, cociente, resto y potencia a nivel de elemento.

### Suma

In [120]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [121]:
# Suma
print(a+b)

[5 7 9]


In [122]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a = a + 1
print(a)

[[2 3 4]
 [5 6 7]]


In [123]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.ones((2, 3))
c = np.add(a, b)
print(c)


[[2. 3. 4.]
 [5. 6. 7.]]


### Resta

In [124]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Resta
print(a-b)

[-3 -3 -3]


In [125]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a = a - 1
print(a)

[[0 1 2]
 [3 4 5]]


In [126]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.subtract(a,b)
print(c)

[-3 -3 -3]


In [127]:
b = np.ones((2, 3))
# print(b)
b1 = np.zeros((10,))
# print(b1)
b2=np.identity(2)
print(b2)

[[1. 0.]
 [0. 1.]]


In [128]:
a = np.array([(1, 2, 3), (4, 5, 6)])
c = np.subtract(a, b)
print(c)

[[0. 1. 2.]
 [3. 4. 5.]]


### Multiplicación

In [129]:
import numpy as np

In [130]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Multiplicación (Producto de vectores entrada por entrada)
# print(np.multiply(a, b))

print(a*b)

[ 4 10 18]


In [131]:
# Multiplicación por escalar

a = np.array([(1, 2, 3), (4, 5, 6)])
a = a * 5
print(a)

[[ 5 10 15]
 [20 25 30]]


In [132]:
b = np.dot(a, 5)
print(b)

[[ 25  50  75]
 [100 125 150]]


In [133]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(2, 2, 2), (3, 3, 3)])
c = np.multiply(a, b)
print(c)

[[ 2  4  6]
 [12 15 18]]


#### Producto escalar de dos vectores

Para realizar el producto escalar de dos vectores se utiliza el operador `@` o el método `u.dot(v)` el cual devuelve el producto escalar de los vectores $u$ y $v$.

In [134]:
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])
print(a @ b)

4


#### Producto de dos matrices

En la teoría de matrices dos arrays se pueden multiplicar si el número de columnas de la primera coincide con el número de filas de la segunda. En Python el producto de dos arrays se realiza utilizando el operador `@` (a partir de Python 3.5) o con la función `np.dot()` de Numpy.

In [135]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)
print(a.dot(b))

[[14 14]
 [32 32]]
[[14 14]
 [32 32]]


### División

In [136]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# print(np.divide(a, b))
print(a/b)

[0.25 0.4  0.5 ]


In [137]:
#Divisiones interesantes
print(1/a)

[1.         0.5        0.33333333]


In [138]:
#Divisiones interesantes
a = np.array([(1, 2, 3), (4, 5, 6)])
# a = a // 2
a = a%3
print(a)

[[1 2 0]
 [1 2 0]]


In [139]:
#Divisiones interesantes
a = np.array([(1, 2, 3), (4, 5, 6)])
a = a / 2
print(a)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [140]:
#División elemento a elemento
a = np.array([(1, 2, 3),(4, 5, 6)])
b = np.array([(1, 1, 1),(2, 2, 2)])
c = np.divide(a, b)
print(c)

[[1.  2.  3. ]
 [2.  2.5 3. ]]


### Módulo

Dividir dos matrices y obtener el resto de la división, elemento a elemento.


In [141]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(1, 1, 1), (2, 2, 2)])
c = np.mod(a, b)
print(c)

[[0 0 0]
 [0 1 0]]


### `numpy.divmod()`


Dividir dos arrays y obtener el cociente y el resto de la división, elemento a elemento.

In [142]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(1, 1, 1), (2, 2, 2)])
c = np.divmod(a, b)
print(c)

(array([[1, 2, 3],
       [2, 2, 3]]), array([[0, 0, 0],
       [0, 1, 0]]))


### Potencia

In [143]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([(1, 2, 3), (4, 5, 6)])

#Potencias
print(a**2)

[1 4 9]


In [144]:
c = c **2
print(c)

[[ 1  4  9]
 [16 25 36]]


In [145]:
#Potencias interesantes
print(a**-1.5)

[1.         0.35355339 0.19245009]


In [146]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.power(a, 5)
print(b)

[[   1   32  243]
 [1024 3125 7776]]


Elevar los elementos de un array a los valores de  otro array, elemento a elemento.


In [147]:
# Potencia elemento a elemento

a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(2, 2, 2), (3, 3, 3)])
c = np.power(a, b)
print(c)

[[  1   4   9]
 [ 64 125 216]]


### `numpy.negative()`

Cambiar el signo a los valores de un array.


In [148]:
a = np.array([(1.5, -2, 3.1), (-4.8, 5.4, -6.6)])
b = np.negative(a)
print(b)

[[-1.5  2.  -3.1]
 [ 4.8 -5.4  6.6]]


### `numpy.rint()`

Redondear todos los valores del array al entero más próximo.


In [149]:
a = np.array([(6.5, 1.5, 3.1), (7.5, 5.4, 6.6)])
b = np.rint(a)
print(b)

[[6. 2. 3.]
 [8. 5. 7.]]


### `numpy.sqrt()`

Calcular la raíz cuadrada, elemento a elemento.


In [150]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.sqrt(a)
print(b)


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


### `numpy.exp()`

In [151]:
a = np.array([(0, 2, 3), (4, 5, 6)])
b = np.exp(a)
print(b)

[[  1.           7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


### Funciones trigonométricas y función logaritmo

In [152]:
import math
a = np.array([(0, 2, 3), (2*math.pi, 5, 6)])
b = np.sin(a)
print(b)

[[ 0.00000000e+00  9.09297427e-01  1.41120008e-01]
 [-2.44929360e-16 -9.58924275e-01 -2.79415498e-01]]


In [153]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.cos(a)
print(b)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [154]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.tan(a)
print(b)

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


## Álgebra Matricial

`Numpy` incorpora funciones para realizar las principales operaciones algebraicas con vectores y matrices. La mayoría de los métodos algebráicos se agrupan en el submódulo `linalg`.

### Módulo de un vector

Para calcular el módulo de un vector se utiliza el siguiente método:

`numpy.linalg.norm(v)`: Devuelve el módulo del vector `v`.

In [155]:
import numpy as np
v = np.array([3, 4])
print(np.linalg.norm(v))

5.0


### Matriz Transpuesta

Para trasponer una matriz se utiliza el método

`array2d.T` : Devuelve la matriz traspuesta de la matriz `array2d`.

In [156]:
import numpy as np
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d.T)

[[1 4]
 [2 5]
 [3 6]]


### Traza de una matriz

La traza de una matriz cuadrada se calcula con el siguiente método:

`array2d.trace()`: Devuelve la traza (suma de las entradas de la matriz en la diagonal principal) de la matriz cuadrada `array2d`.

In [157]:
import numpy as np
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d.trace())

15


### Determinante de una matriz

El determinante de una matriz cuadrada se calcula con la siguiente función:

`numpy.linalg.det(array2d)`: Devuelve el determinante de la matriz cuadrada `array2d`.

In [158]:
import numpy as np
array2d = np.array([[1, 2], [3, 4]])
print(np.linalg.det(array2d))

-2.0000000000000004


### Matriz inversa

La inversa de una matriz se calcula con la siguiente función:

`numpy.inv(array2d)` : Devuelve la matriz inversa de la matriz cuadrada `array2d`.

In [159]:
import numpy as np
array2d = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(array2d))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Eigenvalores de una matriz

Recuerda que dado una transformación lineal $T$, un escalar $\lambda$ es un eigenvalor de $T$ si existe un vector no nulo $\mathbf{v}$ tal que $T(\mathbf{v}) = \lambda \mathbf{v}$.

Los eigenvalores son soluciones de la ecuación característica $\text{det}(A - \lambda I) = 0$, donde $A$ es la matriz correspondiente a la transformación lineal e $I$ es la matriz identidad.

Los eigenvectores correspondientes a un autovalor son los vectores en el espacio propio asociados a ese autovalor.

En Python los eigenvalores de una matriz cuadrada se calculan con la siguiente función: `eigvals(array2d)` la cual devuelve los eigenvalores de la matriz cuadrada `array2d`.

In [160]:
import numpy as np
arrar2d = np.array([[2, 0], [0, 3]])
print(np.linalg.eigvals(arrar2d))

[2. 3.]


### Eigenvectores de una matriz

Los eigenvectores de una matriz cuadrada se calculan con la siguiente función:

`numpy.linalg.eig(array2d)` la cual devuelve los eigenvalores y eigenvectores asociados a la matriz cuadrada `arrar2d`.

In [161]:
import numpy as np
arrar2d = np.array([[2, 0], [0, 3]])
print(np.linalg.eig(arrar2d))

(array([2., 3.]), array([[1., 0.],
       [0., 1.]]))


## Operaciones con arrays de distintas dimensiones


Es una característica avanzada de `Numpy` para realizar operaciones aritméticas con arrays de distintas dimensiones, elemento a elemento, utilizando los símbolos matemáticos (`+`, `-`, `*`, `/`, `//`, `**`). 

In [162]:
array2d = np.ones((5,3))
print(array2d)
matriz = np.array([1, 2, 3])
print(matriz)
suma = array2d + matriz
print(suma)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [163]:
array2d = np.ones((3, 3))
matriz = np.array([[5], [10], [15]])
suma = array2d + matriz
print(suma)

[[ 6.  6.  6.]
 [11. 11. 11.]
 [16. 16. 16.]]


## Funciones estadísticas

### `numpy.mean()`


Calcula la media del ndarray

In [164]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])

print(np.mean(arreglo))     

3.5


#### Media por columnas (eje 0).

In [165]:
medias = np.mean(arreglo,axis=0)  
print(medias)

[2.5 3.5 4.5]


#### Medias por filas (eje 1).

In [166]:
medias = np.mean(arreglo,axis=1)  
print(medias)

[2. 5.]


### `numpy.median()`

Calcula la mediana del ndarray

In [167]:
arreglo = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(np.median(arreglo))     

4.5


#### Medianas por columnas (eje 0).

In [168]:
medianas = np.median(arreglo,axis=0)  
print(medianas)

[3. 4. 5. 6.]


#### Medianas por filas (eje 1).

In [169]:
medianas = np.median(arreglo,axis=1)  
print(medianas)

[2.5 6.5]


### `numpy.std()`

Calcula la desviación estándar del ndarray

In [170]:
print(np.std(arreglo))       

2.29128784747792


#### Desviación estandar por columnas (eje 0).

In [171]:
desviaciones = np.std(arreglo,axis=0)  
print(desviaciones)

[2. 2. 2. 2.]


#### Desviación estandar por filas (eje 1).

In [172]:
desviaciones = np.std(arreglo,axis=1)  
print(desviaciones)

[1.11803399 1.11803399]


### `numpy.var()`

Calcula la varianza del ndarray

In [173]:
print(np.var(arreglo))       

5.25


#### Varianza por columnas (eje 0).

In [174]:
varianzas= np.var(arreglo,axis=0)  
print(varianzas)

[4. 4. 4. 4.]


#### Varianza por filas (eje 1).

In [175]:
varianzas = np.var(arreglo,axis=1)  
print(varianzas)

[1.25 1.25]


### `numpy.min()`

Encuentra el valor mínimo del ndarray


In [176]:
print(np.min(arreglo))

1


#### Valores mínimos por columnas (eje 0).

In [177]:
minimos = np.min(arreglo,axis=0)  
print(minimos)

[1 2 3 4]


#### Valores mínimos por filas (eje 1).

In [178]:
minimos = np.min(arreglo,axis=1)  
print(minimos)

[1 5]


### `numpy.max()`

Encuentra el valor máximo del ndarray

In [179]:
print(np.max(arreglo)) 

8


#### Valores máximos por columnas (eje 0).

In [180]:
maximos = np.max(arreglo,axis=0)  
print(maximos)

[5 6 7 8]


#### Valores máximos por filas (eje 1).

In [181]:
maximos = np.max(arreglo,axis=1)  
print(maximos)

[4 8]


### `numpy.sum()`

Obtener la suma de todos los valores del array.

In [182]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arreglo))


21


#### Obtener la suma de todos los valores por columnas (eje 0)

In [183]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arreglo, axis = 0))


[5 7 9]


#### Obtener la suma de todos los valores por filas (eje 1).

In [184]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arreglo, axis = ))


SyntaxError: invalid syntax (2411293917.py, line 2)

### `numpy.prod()`

Obtener el producto de todos los valores del array.

In [ ]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
print(np.prod(arreglo))


#### Obtener el producto de todos los valores por columnas (eje 0)

In [ ]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
print(np.prod(arreglo, axis = 0))


#### Obtener el producto de todos los valores por filas (eje 1).

In [ ]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
print(np.prod(arreglo, axis = 1))


### `numpy.ptp()`

Obtener la diferencia entre el valor máximo y el mínimo.

In [ ]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
diferencia_min_max = np.ptp(arreglo)
print(diferencia_min_max)

#### Obtener las diferencias entre el valor máximo y el  mínimo por columnas (eje 0).

In [ ]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
diferencia_min_max = np.ptp(arreglo,axis = 0)
print(diferencia_min_max)

#### Obtener las diferencias entre el valor máximo y el  mínimo por filas (eje 1)..

In [ ]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
diferencia_min_max = np.ptp(arreglo,axis = 1)
print(diferencia_min_max)

### `numpy.clip()`

Limitar los valores mínimos y máximos.

In [ ]:
arreglo = np.array([[1, 2, 3], [4, 5, 6]])
np.clip(arreglo,2,5)
print(arreglo)

## Arrays pregenerados

Generear arrays a partir de listas puede ser muy tedioso, por eso `Numpy` integra varias funciones muy útiles para generar arrays de uso común en el álgebra de matrices

### Array de ceros: `numpy.zeros()`

Un array de ceros, todos sus entradas son igual a cero. Podemos generarlos con el método `numpy.zeros` de Numpy.

In [ ]:
import numpy as np
vector_ceros = np.zeros(3)
print(vector_ceros)

Evidentemente podemos generar arrays multidimensionales, pero para ello tenemos que pasarle al método una lista o tupla con la longitud de sus dimensiones:

In [ ]:
matriz_ceros = np.zeros([3,3])
print(matriz_ceros)

### Array de unos: `numpy.eyes()`

Lo mismo podemos hacer pero utilizando el método `numpy.ones()`:

In [ ]:
import numpy as np
matriz_unos = np.ones([3,3])
print(matriz_unos)

### Array  identidad: `numpy.eye()`

Los arrays de identidad son matrices cuadradas (con el mismo número de filas que de columnas) donde todos los valores son ceros a excepción de la diagonal donde son unos. Podemos generarlos con el método `numpy.eye()`:

In [ ]:
matriz_identidad = np.eye(2)
print(matriz_identidad)

### Array de rangos: `numpy.arange()`

También es posible generar arrays a partir de un rango de valores. Para hacerlo utilizaríamos el método `numpy.arange()`:

In [ ]:
array = np.arange(4)
print(array)

In [ ]:
array = np.arange(4.)
print(array)

In [ ]:
array = np.arange(-3, 3)
print(array)


In [ ]:
araya = np.arange(0, 20, 5)
print(array)

### `numpy.linespace()`


La función `numpy.linspace()` en Python se utiliza para generar una secuencia de números espaciados uniformemente dentro de un intervalo especificado.

In [3]:
import numpy as np
secuencia = np.linspace(0, 10, num=1)
print(secuencia)

[0.]


## Solución a sistemas de ecuaciones

In [ ]:
import numpy as np
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))

## Agregar elementos a un array

### `numpy.append()`

In [ ]:
import numpy as np

array = np.array([[1, 2, 3],[4, 5, 6]]) 
print(array)
array2 = np.append(array,[7, 8, 9])
print(array2)

### `numpy.vstack()`, `numpy.hstack()`

In [ ]:
import numpy as np

array_original = np.array([[1, 2, 3],
                            [4, 5, 6]])
nueva_fila = np.array([7, 8, 9])

nuevo_array = np.vstack([array_original, nueva_fila])

print(nuevo_array)

## Métodos para arrays en Numpy


<table>
  <tr>
    <th>Método</th>
    <th>Sintaxis</th>
    <th>Descripción</th>
    <th>Ejemplo</th>
  </tr>
  <tr>
    <td>Array</td>
    <td>numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)</td>
    <td>Crea un array multidimensional.</td>
    <td><code>arr = np.array([1, 2, 3])</code></td>
  </tr>
  <!-- Agrega más filas para los otros métodos -->
  <tr>
    <td>Concatenate</td>
    <td>numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")</td>
    <td>Une una secuencia de arrays a lo largo de un eje existente.</td>
    <td><code>a = np.array([1, 2, 3])<br>b = np.array([4, 5, 6])<br>result = np.concatenate((a, b))</code></td>
  </tr>
  <tr>
    <td>Repeat</td>
    <td>numpy.repeat(a, repeats, axis=None)</td>
    <td>Repite elementos de un array.</td>
    <td><code>a = np.array([1, 2, 3])<br>result = np.repeat(a, 3)</code></td>
  </tr>
  <tr>
    <td>Tile</td>
    <td>numpy.tile(A, reps)</td>
    <td>Construye un array repitiendo A la cantidad de veces especificada por reps.</td>
    <td><code>A = np.array([[1, 2], [3, 4]])<br>result = np.tile(A, (2, 3))</code></td>
  </tr>
  <tr>
    <td>Unique</td>
    <td>numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)</td>
    <td>Encuentra los elementos únicos de un array.</td>
    <td><code>ar = np.array([1, 2, 6, 4, 2, 3, 6])<br>result = np.unique(ar)</code></td>
  </tr>
  <tr>
    <td>Flip</td>
    <td>numpy.flip(m, axis=None)</td>
    <td>Invierte el orden de los elementos en un array a lo largo del eje especificado.</td>
    <td><code>m = np.arange(8).reshape((2,2,2))<br>result = np.flip(m, axis=1)</code></td>
  </tr>
  <tr>
    <td>Full</td>
    <td>numpy.full(shape, fill_value, dtype=None, order='C')</td>
    <td>Crea un array con una forma dada y todos sus elementos establecidos en un valor fijo.</td>
    <td><code>shape = (2, 2)<br>result = np.full(shape, 7)</code></td>
  </tr>
  <tr>
    <td>Insert</td>
    <td>numpy.insert(arr, obj, values, axis=None)</td>
    <td>Inserta valores a lo largo del eje dado antes de los índices dados.</td>
    <td><code>arr = np.array([[1, 1], [2, 2], [3, 3]])<br>result = np.insert(arr, 1, 5, axis=1)</code></td>
  </tr>
  <tr>
    <td>Split</td>
    <td>numpy.split(ary, indices_or_sections, axis=0)</td>
    <td>Divide un array en múltiples sub-arrays.</td>
    <td><code>ary = np.arange(9)<br>result = np.split(ary, 3)</code></td>
  </tr>
  <tr>
    <td>Diagonal</td>
    <td>numpy.diagonal(a, offset=0, axis1=0, axis2=1)</td>
    <td>Devuelve la diagonal de un array o las diagonales especificadas.</td>
    <td><code>a = np.arange(16).reshape((4,4))<br>result = np.diagonal(a)</code></td>
  </tr>
  <tr>
    <td>Argmax</td>
    <td>numpy.argmax(a, axis=None, out=None)</td>
    <td>Devuelve los índices del valor máximo a lo largo de un eje.</td>
    <td><code>a = np.array([1, 2, 3, 2, 1])<br>result = np.argmax(a)</code></td>
  </tr>
  <tr>
    <td>Argmin</td>
    <td>numpy.argmin(a, axis=None, out=None)</td>
    <td>Devuelve los índices del valor mínimo a lo largo de un eje.</td>
    <td><code>a = np.array([1, 2, 3, 2, 1])<br>result = np.argmin(a)</code></td>
  </tr>
  <tr>
    <td>Max</td>
    <td>numpy.max(a, axis=None, out=None, keepdims=False, initial=<no value>, where=True)</td>
    <td>Devuelve el valor máximo a lo largo de un eje.</td>
    <td><code>a = np.array([1, 2, 3, 2, 1])<br>result = np.max(a)</code></td>
  </tr>
  <tr>
    <td>Min</td>
    <td>numpy.min(a, axis=None, out=None, keepdims=False, initial=<no value>, where=True)</td>
    <td>Devuelve el valor mínimo a lo largo de un eje.</td>
    <td><code>a = np.array([1, 2, 3, 2, 1])<br>result = np.min(a)</code></td>
  </tr>
  <tr>
    <td>Mean</td>
    <td>numpy.mean(a, axis=None, dtype=None, out=None, keepdims=False)</td>
    <td>Calcula la media aritmética a lo largo del eje especificado.</td>
    <td><code>a = np.array([1, 2, 3, 2, 1])<br>result = np.mean(a)</code></td>
  </tr>
  <tr>
    <td>Median</td>
    <td>numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)</td>
    <td>Calcula la mediana a lo largo del eje especificado.</td>
    <td><code>a = np.array([1, 2, 3, 2, 1])<br>result = np.median(a)</code></td>
  </tr>
  <tr>
    <td>Cumsum</td>
    <td>numpy.cumsum(a, axis=None, dtype=None, out=None)</td>
    <td>Devuelve la suma acumulativa de los elementos a lo largo de un eje.</td>
    <td><code>a = np.array([1, 2, 3, 4])<br>result = np.cumsum(a)</code></td>
  </tr>
  <tr>
    <td>Cumprod</td>
    <td>numpy.cumprod(a, axis=None, dtype=None, out=None)</td>
    <td>Devuelve el producto acumulativo de los elementos a lo largo de un eje.</td>
    <td><code>a = np.array([1, 2, 3, 4])<br>result = np.cumprod(a)</code></td>
  </tr>
  <tr>
    <td>Diff</td>
    <td>numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)</td>
    <td>Calcula la diferencia entre elementos consecutivos a lo largo del eje especificado.</td>
    <td><code>a = np.array([1, 3, 6, 10])<br>result = np.diff(a)</code></td>
  </tr>
</table>