## assert

El uso de assert en Python nos permite realizar comprobaciones. Si la expresión contenida dentro del mismo es False, se lanzará una excepción, concretamente AssertionError. Veamos un ejemplo:

In [ ]:
assert(1==2)

AssertionError: 

Es decir, si el contenido existente dentro del assert es igual a False, se lanzará la excepción. Se podría conseguir el mismo resultado haciendo lo siguiente, pero el uso de assert() resulta más cómodo.

In [ ]:
if condicion:
    raise AssertionError()

NameError: name 'condicion' is not defined

Podemos también añadir un texto con información relevante acerca del assert().

In [ ]:
assert 1==2, "El assert falló"

AssertionError: El assert falló

Aunque mucho cuidado, ya que la expresión anterior no es equivalente a la siguiente, siendo la misma errónea. Esto se debe a que en realidad se está evaluando bool((False, "El assert falló")), lo que resulta ser siempre True. De hecho el siguiente código no lanzaría una excepción, cuando realmente se esperaría que lo hiciera.

### assert() en funciones

Puede resultar útil usar `assert()` cuando queremos realizar alguna comprobación, como podría ser dentro de una función. En el siguiente ejemplo tenemos una función `suma()` que sólo suma las variables si son números enteros.

In [ ]:
def suma(a, b):
    assert(type(a) == int)
    assert(type(b) == int)
    return a+b

In [ ]:
suma(3.0, 5.0)

SyntaxError: invalid syntax (553101005.py, line 1)

In [ ]:
suma(3, 5)

8

## Pregunta 1

#### Escriba una función en Python que genere una contraseña aleatoria. La contraseña debe tener una longitud aleatoria de entre 8 y 12 caracteres. Cada carácter debe seleccionarse al azar de las posiciones 33 a 126 en la tabla ASCII. La función no recibirá ningún parámetro y  devolverá la contraseña generada aleatoriamente como único resultado. Muestre la contraseña generada aleatoriamente en el programa principal de su archivo (fuera de la función). 

#### **Sugerencia:** Posiblemente la función `chr` resulte util para resolver este ejercicio.

## Pregunta 2

#### Escribe un programa en Python que solicite al usuario un número entero (usa r `try-except` para validar entrada) e imprima  la suma de sus dígitos. Por ejemplo si el usuario ingresa `3114`, entonces se debe imprimir `9` porque $3+1+4+1=9$

In [ ]:
import numpy as np

def metodo_babilonico(a0,numero,num_iter,epsilon):
    i = 1
    a=a0
    a1 = 0.5*(numero/a0 + a0 )
    er = abs(a1- a0)
    iteraciones =[[i,a0,a1,er]] 
    print("| {:^15} | {:^30} | {:^30} | {:^30} |".format("# iteración","a_{n-1}", "a_n", "|a_{n-1} - a_n|"))
    print("{:^112}".format("_"*112))
    print("| {:^15} | {:^30.20f} | {:^30.20f} | {:^30.20f} |".format(i,a0, a1, er))
    while i < num_iter and er >epsilon:
        i +=1
        a0 = a1
        a1 = a0 
        a1 = 0.5*(numero/a0 + a0 )
        er = abs(a1- a0)
        iteraciones.append([i,a0,a1,er])
        print("| {:^15} | {:^30.20f} | {:^30.20f} | {:^30.20f} |".format(i,a0, a1, er))
    print("\n La aproximación a la raiz cuadrada de {} utilizando el método babilonicocon una aproximación inicial de {}, \n bajo {} iteraciones y un error relativo de {} es: {:.20f}".format(numero,a,num_iter,epsilon,a1))
    return a1

apoximación = metodo_babilonico(123456,4,100,0.1)
    

In [1]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a diagonal matrix with diagonal elements 1, 2, 3, 4, 5 using np.diag()
x = np.diag([1, 2, 3, 4, 5])

# Printing the diagonal matrix 'x'
print(x) 

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [2]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a 10x10 matrix filled with ones using np.ones()
x = np.ones((10, 10))

# Setting the inner values of the matrix 'x' (excluding the borders) to 0 using slicing
x[1:-1, 1:-1] = 0

# Printing the modified matrix 'x'
print(x) 


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [3]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'm' containing integers from 10 to 21 and reshaping it into a 3x4 matrix using np.arange() and .reshape()
m = np.arange(10, 22).reshape((3, 4))

# Printing the array 'm' representing a 3x4 matrix
print(m) 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [9]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'x' containing integers from 0 to 20 using np.arange()
x = np.arange(11)

# Printing a message indicating the original vector 'x'
# print("Original vector:")
print(x)

# Printing a message indicating changing the sign of numbers in the range from 9 to 15
# Using boolean indexing, multiplying elements between 9 and 15 by -1 to change their sign
x[(x >= 3) & (x <= 75)] *= -1

# Printing the modified vector 'x'
# print("After changing the sign of the numbers in the range from 9 to 15:")
print(x) 

[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1   2  -3  -4  -5  -6  -7  -8  -9 -10]


In [10]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a 4x4 matrix filled with zeros using np.zeros()
x = np.zeros((4, 4))

# Setting elements in alternate rows and columns to 1
# Setting elements in even rows (0-based indexing) and odd columns to 1
x[::2, 1::2] = 1

# Setting elements in odd rows and even columns to 1
x[1::2, ::2] = 1

# Printing the modified matrix 'x'
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [12]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Importing the 'os' module for operating system-dependent functionality
import os

# Creating a NumPy array 'x' with integers from 0 to 11 and reshaping it to a 4x3 matrix using np.arange() and .reshape()
x = np.arange(12).reshape(4, 3)

# Printing a message indicating the original array 'x'
# print("Original array:")
print(x)

# Creating a string 'header' containing column names 'col1 col2 col3'
header = 'col1 col2 col3'

# Saving the array 'x' into a text file named 'temp.txt' using np.savetxt()
# Specifying the format as "%d" (integer) and including a header with column names
np.savetxt('temp.txt', x, fmt="%d", header=header)

# Printing a message indicating the content of the text file after loading
# print("After loading, content of the text file:")

# Loading the data from 'temp.txt' into the variable 'result' using np.loadtxt()
result = np.loadtxt('temp.txt')

# Printing the loaded data 'result' from the text file
print(result) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [14]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array of even integers from 30 to 70 (inclusive) with a step size of 2 using np.arange()
array = np.arange(30, 71, 2)

# Printing a message indicating an array of all the even integers from 30 to 70
# print("Array of all the even integers from 30 to 70")

# Printing the array of all the even integers from 30 to 70
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [16]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array of integers from 30 to 70 using np.arange()
array = np.arange(30, 71)

# Printing a message indicating an array of integers from 30 to 70
# print("Array of the integers from 30 to 70")

# Printing the array of integers from 30 to 70
print(array) 


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [17]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array 'x' using arange() function with values from 12 to 37 (inclusive)
x = np.arange(12, 38)

# Printing the original array 'x' containing values from 12 to 37
print("Original array:")
print(x)

# Reversing the elements in the array 'x' and printing the reversed array
print("Reverse array:")
x = x[::-1]
print(x) 

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [19]:
import numpy as np

# Definir una matriz de ejemplo
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Obtener las dimensiones de la matriz
filas, columnas = matriz.shape

# Crear una matriz invertida
matriz_invertida = np.zeros_like(matriz)

# Invertir la matriz manualmente
for i in range(filas):
    for j in range(columnas):
        matriz_invertida[filas - 1 - i, columnas - 1 - j] = matriz[i, j]

# Imprimir la matriz original
print("Matriz original:")
print(matriz)

# Imprimir la matriz invertida
print("Matriz invertida:")
print(matriz_invertida)


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz invertida:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [23]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array 'array1' using NumPy
array1 = np.array([0, 1, 2, 3, 4])

# Printing the contents of 'array1'
print("Vector1: ", array1)

# Creating a Python list 'array2'
array2 = [0, 2]

# Printing the contents of 'array2'
print("Vector2: ", array2)

# Comparing each element of 'array1' with 'array2'
print("Resultado")
print(np.in1d(array1, array2))


Vector1:  [0 1 2 3 4]
Vector2:  [0, 2]
Resultado
[ True False  True False False]


In [24]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array 'array1' using NumPy
array1 = np.array([0, 10, 20, 40, 60])

# Printing the contents of 'array1'
print("Array1: ", array1)

# Creating a Python list 'array2'
array2 = [10, 30, 40]

# Printing the contents of 'array2'
print("Array2: ", array2)

# Finding the common values between 'array1' and 'array2'
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [27]:
Z = np.random.randint(0,10,(3,3))
print(Z,"\n")
print(Z[Z[:,1].argsort()])

[[0 0 7]
 [2 0 9]
 [7 2 1]] 

[[0 0 7]
 [2 0 9]
 [7 2 1]]
